.\"
.\" Copyright (c) 2017, 2018 Steven Roberts <sroberts@fenderq.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 3 2018 $
.Dt ANKH 1
.Os
.Sh NAME
.Nm ankh
.Nd cryptographically encrypt and decrypt
.Sh SYNOPSIS
.Nm ankh
.Fl B
.Op Fl a Ar algo
.Op Fl d
.Op Fl k Ar keyfile
.Op Fl s Ar seckey
.Fl p Ar pubkey
.Nm ankh
.Fl G
.Op Fl a Ar algo
.Op Fl k Ar keyfile
.Op Fl m Ar mode
.Fl p Ar pubkey
.Fl s Ar seckey
.Nm ankh
.Fl P
.Op Fl a Ar algo
.Op Fl d
.Op Fl k Ar keyfile
.Fl p Ar pubkey
.Fl s Ar seckey
.Nm ankh
.Fl S
.Op Fl a Ar algo
.Op Fl d
.Op Fl k Ar keyfile
.Op Fl m Ar mode
.Nm ankh
.Fl V
.\" OLD
.Sh DESCRIPTION
The
.Nm
utility will read from stdin and write to stdout.
The mode of operation is selected with the following options:
.Bl -tag -width Ds
.It Fl B
Sealed boxes are designed to anonymously send messages to a recipient
given its public key.
.It Fl G
Generate a new key pair.
Keynames should follow the convention of
.Pa keyname.pub
and
.Pa keyname.sec
for the public and secret keys, respectively.
.It Fl P
Public-key authenticated encryption.
Using public-key authenticated encryption, Bob can encrypt a confidential
message specifically for Alice, using Alice's public key.
.It Fl S
Secret-key authenticated encryption used to encrypt/sign and verify/decrypt
messages.
The key is derived from a passphrase.
.It Fl V
Print out version information.
.El
.Pp
The other options are as follows:
.Bl -tag -width Dsskeyfile
.It Fl a Ar algo
Set the
.Ar algo
for key derivation.
This can either be argon2i or argon2id, otherwise the libsodium default
value will be used.
.It Fl d
Decrypt the stream.
.It Fl k Ar keyfile
Read passphrase from
.Ar keyfile .
.It Fl m Ar mode
Set the
.Ar mode
of key derivation.
This is a numerical value from one of the following:
.Bl -enum
.It
For interactive, online operations.
This requires 64 MiB of dedicated RAM.
.It
This is the default mode.
This requires 256 MiB of dedicated RAM.
.It
For highly sensitive data and non-interactive operations.
This requires 1024 MiB of dedicated RAM.
.El
.It Fl p Ar pubkey
Public key file.
.It Fl s Ar seckey
Secret key file.
.El
.Sh EXAMPLES
Encrypt a file using a passphrase:
.Dl $ ankh -S < plaintext.file > ciphertext.file
.Pp
Decrypt a file using a passphrase:
.Dl $ ankh -S -d < ciphertext.file > plaintext.file.2
.Pp
Generate a new key pair:
.Dl $ ankh -G -p alice.pub -s alice.sec
.Pp
Encrypt a file using sealed box:
.Dl $ ankh -B -p alice.pub < plaintext.file > ciphertext.file
.Pp
Decrypt a file using sealed box:
.Dl $ ankh -B -p alice.pub -s alice.sec < ciphertext.file > plaintext.file.2
.Pp
Encrypt a file from Alice to Bob using public key:
.Dl $ ankh -P -p bob.pub -s alice.sec < plaintext.file > ciphertext.file
.Pp
Decrypt a file from Alice to Bob using public key:
.Dl $ ankh -P -p alice.pub -s bob.sec < ciphertext.file > plaintext.file.2
.Sh AUTHORS
.An Steven Roberts <sroberts@fenderq.com>
