.\"
.\" Copyright (c) 2017 Steven Roberts <sroberts@fenderq.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 24 2017 $
.Dt ANKH 1
.Os
.Sh NAME
.Nm ankh
.Nd file encryption utility
.Sh SYNOPSIS
.Nm ankh
.Op Fl dv
.Op Fl m Ar mode
.Ar infile
.Ar outfile
.Sh DESCRIPTION
.Pp
The
.Nm
utility will read from
.Ar infile
and write to
.Ar outfile .
Encryption is done by default unless the
.Fl d
option is used.
The
.Fl m
option controls the key derivation function.
The
.Fl v
option prints extra details about the operation being performed.
.Pp
The key derivation function uses Argon2i. The encryption process uses
the XSalsa20 stream cipher. Authentication is done with Poly1305 MAC.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Decrypt the input data.
.It Fl m Ar mode
Modes for the key derivation function.
.Bl -tag -width compact
.It Ar 1
Requires 32 Mb of dedicated RAM
.It Ar 2
Requires 128 Mb of dedicated RAM, and takes about 0.7
seconds on a 2.8 Ghz Core i7 CPU
.It Ar 3
Requires 512 Mb of dedicated RAM, and takes about
3.5 seconds on a 2.8 Ghz Core i7 CPU (default)
.El
.It Fl v
Produce verbose output.
.El
.Sh AUTHORS
.An Steven Roberts <sroberts@fenderq.com>
.Sh CAVEATS
The mode is not stored in the encrypted file.
